### ISSUE TITLE
It's slow to train my own data

### ISSUE THREAD

**Issue by baolinhu** [ijkguo/mx-rcnn#101]
Training with VOC data sets, 5.5imgs/second

Using your own dataset (converted to VOC format), only 1.7imgs/second

It's all 4 1080Ti, and the parameters are the same.

**Comment by Ram124** [comment]
It could be of 2 reasons for slow rate, 1 is your input image size.. and second is your backbone network.
I tried with vgg16 as backbone, speed was 2.3 samples/sec
with resent 50, speed is 2.5 samples/sec
But with resnet 18 , speed is 6.2 samples/sec.
I am using aws instance p2.large.. single GPU.

**Comment by ijkguo** [comment]
It is possible if your dataset has much more objects in one image. Speed is slower most likely due to symdata.bbox_overlaps function, where v5.1 release had a Cython extension.

**Comment by baolinhu** [comment]
@ijkguo You are right.My dataset has much more objects than voc or coco.It means I should use the v5.1 ,not the latest version?
Thanks.

**Comment by ijkguo** [comment]
Unfortunately yes for now.
