### ISSUE TITLE
How to avoid using JPEG images in pascal format

### ISSUE THREAD

**Issue by Ram124** [ijkguo/mx-rcnn#103]
Hello Everyone,

I am currently using Pascal format dataset with jpeg images, annotations, imagesets.

I do not want to save the images as there will some loss of information when generating jpeg images in my application. Insead i wanna make use of Numpy array or other way to feed the input image data..

How can i do that? 
Where in the code is JPEG image is getting converted to numpy array..?

Can someone help me out in this. 
Where exactly i can feed the direct numpy array of input image instead of JPEG image..

**Comment by ijkguo** [comment]
JPEG image getting converted to numpy array `symdata/image.py`

**Comment by Ram124** [comment]
So in the first block, im_tensor is created for every image one by one ?? 
There i need to give the numpy array of each image??
How can i change the code to take the input as numpy array? 
I need something to feed all the data at once, 
Not by storing each numpy array and loading it everytime..

**Comment by ijkguo** [comment]
`symdata/loader.py` call `symdata.image.get_image` to read source image.
