### ISSUE TITLE
Not an issue - It works Windows and Python3

### ISSUE THREAD

**Issue by LouiseAbela** [ijkguo/mx-rcnn#77]
MX-RCNN works with with Windows 10 and Python3 (3.6). But for now I tried it only with pre-trained models for now and on CPU. 

Some changes I done to make it work were:
 - Changing CPickle to Pickle in imports
 - Compiling the seutp.py before running for pycocotools and cython using (python setup.py build_ext install)
 - Changing  the 'import _mask' to 'from pycocotools import _mask' as if not in python3 you'll get relative reference error
 - Refactor package io as it conflicts with other installation (but that might be just my case)

I think I changed some more minor things, but forgot what these were.

**Comment by MonsterPeng** [comment]
can you give more details about how to deploy this on Windows

**Comment by LouiseAbela** [comment]
What kind of details?

**Comment by ijkguo** [comment]
Recently cython packages removed completely and python 3 support added. So no additional configuration anymore.
