### ISSUE TITLE
how to print out each category's accuracy using faster rcnn?

### ISSUE THREAD

**Issue by yian2271368** [ijkguo/mx-rcnn#80]
i am doing a object detection project for 9 classes(including background), but in the end it prints out the loss and classfication score for overall classes. so i am wondering how could I print out loss and acc(ie, rnploss&acc, rcnn loss&acc) for each class?

**Comment by precedenceguo** [comment]
You might need to write metrics. See rcnn/core/metric.py for examples.

**Comment by Ram124** [comment]
@ijkguo I have done training on 2 classes..
I got this results after 5 epochs.

INFO:root:testing 197/200 data 0.0125s net 0.3531s post 0.0002s
INFO:root:testing 198/200 data 0.0126s net 0.3365s post 0.0005s
INFO:root:testing 199/200 data 0.0150s net 0.3315s post 0.0003s
INFO:root:Writing pedestrian VOC results file
INFO:root:Writing bicycle VOC results file
INFO:root:VOC07 metric? Y
INFO:root:AP for pedestrian = 0.8070
INFO:root:AP for bicycle = 0.8183
INFO:root:Mean AP = 0.8126

Now i want to use this model to predict the classes. 
should i use demo.py to visualize the results or should i do something else?

Actually i executed demo.py . Here i could feed only 1 image as input to check the results. Is there any other way where i can give some 100's of images and visualize the output on all images.?

When i do demo.py on single image. i am getting only  1 class(box) per image. i am not getting 2 boxes on single image. what is the reason for this??

Please provide me some solution for this.

**Comment by ijkguo** [comment]
Redirect to https://github.com/ijkguo/mx-rcnn/issues/95.
