### ISSUE TITLE
train_end2end vs train_alternate

### ISSUE THREAD

**Issue by yaoliUoA** [ijkguo/mx-rcnn#83]
Hi, 

For training faster-RCNN, The repository provides two methods, train_alternate vs train_end2end. 
I wonder which methods are the released models (ie, the models in the table in readme) are trained on? 
Has someone compare the performance of train_alternate and train_end2end? 

I have trained a faster RCNN using train_end2end but it does not work well on the test set. I wonder maybe I should switch to train_alternate,  as in the original Faster R-CNN paper, the authors used thetrain_alternate way (train RPN first, and then fixed the propsals to train Fast R-CNN) . I am not sure 
if train_end2end already works in theory (for example, the Faster R-CNN authors said it may not converage if using train_end2end in the paper).

**Comment by ijkguo** [comment]
Alternate training is deprecated now.
