### ISSUE TITLE
ResNet101 as base net cannot detect any object?

### ISSUE THREAD

**Issue by 315386775** [ijkguo/mx-rcnn#86]
# Training stage. 
INFO:root:Epoch[5] Batch [23280]	Speed: 4.98 samples/sec	Train-RPNAcc=0.995354,	RPNLogLoss=0.012738,	RPNL1Loss=0.234201,	RCNNAcc=0.976568,	RCNNLogLoss=0.063541,	RCNNL1Loss=0.538337,	
INFO:root:Epoch[5] Train-RPNAcc=0.995354
INFO:root:Epoch[5] Train-RPNLogLoss=0.012738
INFO:root:Epoch[5] Train-RPNL1Loss=0.234201
INFO:root:Epoch[5] Train-RCNNAcc=0.976568
INFO:root:Epoch[5] Train-RCNNLogLoss=0.063541
INFO:root:Epoch[5] Train-RCNNL1Loss=0.538337 

# Test stage
The AP == 0.00

# Demo stage
I just changed the demo.py as :
(1)from rcnn.symbol import get_resnet_test
(2)symbol = get_resnet_test(num_classes=config.NUM_CLASSES, num_anchors=config.NUM_ANCHORS)
Then run: python demo.py --prefix ./model/e2e --epoch 10 
All result as the follow:
results saved to ./reanetResult/000090.bmp class ---- [[x1, x2, y1, y2, confidence]]

How to solve this problem?

**Comment by precedenceguo** [comment]
Note that in `rcnn.config` PIXEL_MEANS should be set to 0 for ResNet.

**Comment by ijkguo** [comment]
Closed due to inactivity.
