### ISSUE TITLE
Training using our own dataset

### ISSUE THREAD

**Issue by Ram124** [ijkguo/mx-rcnn#93]
I have successfully executed demo.py.
Now i am trying to run on my own dataset.
I have made changes to the following things.

In config.py,

 

default.dataset = 'RangeDET'

default.image_set = 'train'

default.test_image_set = 'test'

default.root_path = 'data'

default.dataset_path = 'data/range'

in rcnn/dataset/__init__.py 
I have added
from .range_det import RangeDET

I have created a new Python file like pascal_voc.py. 
named it as range_det.py

But i am getting error something like this
Can someone tell me what could be the problem??
ubuntu@ip-172-31-10-202:~/mx-rcnn$ python train_end2end.py
Traceback (most recent call last):
  File "train_end2end.py", line 178, in <module>
    main()
  File "train_end2end.py", line 171, in main
    args = parse_args()
  File "train_end2end.py", line 146, in parse_args
    generate_config(args.network, args.dataset)
  File "/home/ubuntu/mx-rcnn/rcnn/config.py", line 159, in generate_config
    for k, v in dataset[_dataset].items():
KeyError: 'RangeDET

Any help is really appreciated

**Comment by ijkguo** [comment]
This global config is outdated. But based on your error message, you may try to add RangeDET to the dataset dict.

**Comment by Ram124** [comment]
@ijkguo  Where should i do that??
Is it in config file.?
