### ISSUE TITLE
Can we use Batch size more than 1

### ISSUE THREAD

**Issue by Ram124** [ijkguo/mx-rcnn#96]
I have images of more than 15000.
I want to reduce the compute power. So i wanna make use of batch size of more than 1.
Can it be possible to use more than 1? If yes, Please let me know how.

Your help is really appreciated.
P.S : You have done a Simplified version of mxnet- Faster rcnn. Great job

**Comment by ijkguo** [comment]
Asked and answered. https://github.com/apache/incubator-mxnet/issues/9823
